name: "CI/CD: Build and Deploy app to Digital Ocean"

on:
  push:
    branches: ["deploy"]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run build --if-present
      - name: Change to frontend directory
        run: cd frontend && npm install && npm run build --if-present
      - name: Start the application with pm2
        run: pm2 start default
